apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pam-min-side-microfrontend # Change this to your application name
  namespace: teampam # Change this to your namespace
  labels:
    team: teampam # Change this to your team name
spec:
  tokenx:
    enabled: true
  image: {{ image }}
  port: 3000
  liveness:
    path: /api/internal/isAlive
    initialDelay: 10
  readiness:
    path: /api/internal/isReady
    initialDelay: 10
  ingresses:
    - https://pam-min-side-microfrontend.nav.no
  replicas:
    min: 2
    max: 2
  accessPolicy:
    inbound:
      rules:
        - application: tms-min-side
          namespace: min-side
  resources:
    limits:
      memory: 768Mi
    requests:
      cpu: "20m"
      memory: 128Mi
